SKN 341 add no linked campaign validation
Salesfactory/rest-api-skynet pull request #82
Opened 2023-09-22 04:01 UTC by Alexjes98

2023-09-22 12:37 UTC, PedroLabrador commented on src/cronjobs.js
> +        cron.schedule('* * * * *', async () => {
Esto revisa cada minuto no cada dia a las 9

2023-09-22 12:58 UTC, PedroLabrador commented on src/cronjobs.js
> +                                !campaign.big_query_id
Está seguro que este es el atributo que está dentro del campaign? yo creo que deberia ser bigquery_campaign_id

2023-09-22 13:00 UTC, PedroLabrador requested changes
SKN-341 es para marcar grupos de campañas como linked? no es para mandar correos?

2023-09-22 13:45 UTC, Alexjes98 commented on src/cronjobs.js
> +        cron.schedule('* * * * *', async () => {
cierto, fixed

2023-09-22 13:46 UTC, Alexjes98 commented on src/cronjobs.js
> +                                !campaign.big_query_id
fixed

2023-09-22 13:49 UTC, PedroLabrador commented on src/cronjobs.js
> +        cron.schedule('* 9 * * *', async () => {
el cronjob deberia ser 0 9 * * * no * 9 * * *  ahora esta corriendo cada minuto despues de las 9

2023-09-22 13:49 UTC, PedroLabrador requested changes
mal cronjob

2023-09-22 13:53 UTC, PedroLabrador commented on src/cronjobs.js
> +        cron.schedule('* 9 * * *', async () => {
https://crontab.guru/#0_9_*_*_*

2023-09-22 16:19 UTC, PedroLabrador approved these changes
Este PR solo verifica que estén linkeados? SKN-341 aun necesita enviar la notificacion a las 9am, la verificacion como tal no es que se haga diariamente a las 9am, Si no la notificación.

2023-09-22 20:59 UTC, Alexjes98 commented
si, voy a agregar las notificaciones cuando esté disponible en develop la función de generar notificaciones y enviar al correo

2023-09-25 13:37 UTC, maacaro requested changes
@Alexjes98 aca nofaltaria un test para el controler o modificar el controler

2023-09-25 14:02 UTC, merged